@startuml
rectangle "UI" {  
    rectangle "index.html"
    rectangle "postmaster.html"
    rectangle "postbook.html"
    rectangle "confirmdelete.html"
    rectangle "error.html"
}

rectangle "Backend" {
    rectangle "app"
    rectangle "routes"
    rectangle "methods"
}

database "Database" {
    rectangle "Reference"
}

interface HTTP

index.html <--> postbook.html
index.html <--> postmaster.html
index.html <--> confirmdelete.html
postbook.html <--> error.html  
postmaster.html <--> error.html
confirmdelete.html <--> error.html


UI -- HTTP
HTTP - routes


app --> routes
routes - methods
methods -- Database


@enduml