@startuml
rectangle "UI" {  
    rectangle "index.html"    
    rectangle "postarticle.html"    
    rectangle "postbook.html"
    rectangle "postphdthesis.html"
    rectangle "postmasterthesis.html"    
    rectangle "confirmdelete.html"
    'rectangle "error.html"
}

rectangle "Backend" {
    rectangle "app"
    rectangle "routes"
    rectangle "methods"
}

database "Database" {
    rectangle "Reference"
}

interface HTTP

index.html <--> postarticle.html
index.html <--> postbook.html
index.html <--> postphdthesis.html
index.html <--> postmasterthesis.html
index.html <-right-> confirmdelete.html
'postbook.html <--> error.html  
'postmasterthesis.html <--> error.html
'confirmdelete.html <--> error.html


UI -- HTTP
HTTP - routes


app --> routes
routes - methods
methods -- Database


@enduml