@startuml
left to right direction

actor "User" as user
actor "Application" as app
 
usecase "Add reference" as addRef
usecase "Add article" as addArticle
usecase "Add book" as addBook
usecase "Add phd thesis" as addPhd
usecase "Add master thesis" as addMasterthesis
usecase "Modify reference" as modifyRef
usecase "Delete reference" as deleteRef
usecase "Display references" as displayRef
usecase "Download references" as downloadRef
usecase "Download as Bibtex" as downloadBibtex

user -- addRef
addArticle --|> addRef
addBook --|> addRef
addRef <|-- addPhd
addRef <|-- addMasterthesis
addRef -- app

user -- modifyRef
modifyRef -- app

user -- deleteRef
deleteRef -- app

user -- displayRef
displayRef -- app

user -- downloadRef
downloadBibtex --|> downloadRef
downloadRef -- app
@enduml